import type { Product, TrainingPlan } from "@/types";

export const MOCK_PLANS: Partial<TrainingPlan>[] = [
  {
    id: "1",
    slug: "hypertrophy-101",
    name: "Hypertrophy 101",
    short_description: "Build serious muscle mass over 12 weeks with this science-based hypertrophy program.",
    description: "This 12-week program focuses on progressive overload, varied rep ranges, and strategic exercise selection to maximize muscle growth. Designed for intermediate lifters looking to break through plateaus.",
    price: 49.99,
    compare_at_price: 99.99,
    duration_weeks: 12,
    difficulty: "intermediate",
    goal: "Muscle Building",
    category: "Bodybuilding",
    equipment_needed: ["Barbell", "Dumbbells", "Cables", "Machines"],
    is_active: true,
    is_featured: true,
    subscriber_count: 5430,
    average_rating: 4.9,
    review_count: 892,
  },
  {
    id: "2",
    slug: "shred-60",
    name: "Shred 60",
    short_description: "A high-intensity 60-day fat loss protocol combining lifting and conditioning.",
    description: "Get shredded for summer. This program combines heavy compound lifts to maintain muscle with metabolic conditioning to torch fat.",
    price: 39.99,
    compare_at_price: 79.99,
    duration_weeks: 8,
    difficulty: "advanced",
    goal: "Fat Loss",
    category: "Metabolic Conditioning",
    equipment_needed: ["Dumbbells", "Kettlebells", "Bodyweight"],
    is_active: true,
    is_featured: true,
    subscriber_count: 8200,
    average_rating: 4.7,
    review_count: 1205,
  },
  {
    id: "3",
    slug: "strength-foundations",
    name: "Strength Foundations",
    short_description: "Perfect for beginners. Master the big three lifts and build a base of raw strength.",
    description: "Learn proper form for the squat, bench press, and deadlift while building foundational strength that will serve you for a lifetime of lifting.",
    price: 29.99,
    compare_at_price: null,
    duration_weeks: 6,
    difficulty: "beginner",
    goal: "Strength",
    category: "Powerlifting",
    equipment_needed: ["Barbell", "Squat Rack", "Bench"],
    is_active: true,
    is_featured: false,
    subscriber_count: 12450,
    average_rating: 4.8,
    review_count: 3100,
  }
];

export const MOCK_PRODUCTS: Partial<Product>[] = [
  {
    id: "1",
    slug: "gold-standard-whey",
    name: "Gold Standard 100% Whey",
    short_description: "24g protein per serving, 5.5g BCAAs",
    description: "Post-workout muscle support and recovery. Each serving provides 24 grams of high-quality whey protein primarily from Whey Protein Isolate.",
    price: 34.99,
    compare_at_price: 44.99,
    average_rating: 4.8,
    review_count: 2847,
    flavor: "Double Rich Chocolate",
    is_featured: true,
    category: { id: "1", slug: "protein", name: "Protein", description: null, image_url: null, parent_id: null, position: 1, is_active: true },
    brand: { id: "1", slug: "optimum-nutrition", name: "Optimum Nutrition", description: null, logo_url: null, website_url: null, is_active: true },
    ingredients: "Protein Blend (Whey Protein Isolate, Whey Protein Concentrate, Whey Peptides), Cocoa, Natural and Artificial Flavor, Lecithin, Creamer, Salt, Acesulfame Potassium, Sucralose, Lactase.",
    servings: 29,
    serving_size: "1 Scoop (30.4g)",
  },
  {
    id: "2",
    slug: "c4-original-pre-workout",
    name: "C4 Original Pre-Workout",
    short_description: "150mg caffeine, explosive energy",
    description: "C4 Original is built to take your energy, muscular endurance, and pumps to the next level.",
    price: 29.99,
    compare_at_price: null,
    average_rating: 4.6,
    review_count: 1923,
    flavor: "Fruit Punch",
    is_featured: true,
    category: { id: "2", slug: "pre-workout", name: "Pre-Workout", description: null, image_url: null, parent_id: null, position: 2, is_active: true },
    brand: { id: "2", slug: "cellucor", name: "Cellucor", description: null, logo_url: null, website_url: null, is_active: true },
    ingredients: "CarnoSyn Beta-Alanine, Creatine Nitrate (NO3-T), Arginine AKG, Explosive Energy Blend, Vitamin C.",
    servings: 30,
    serving_size: "1 Scoop (6g)",
  },
  {
    id: "3",
    slug: "creatine-monohydrate",
    name: "Micronized Creatine Monohydrate",
    short_description: "5g pure creatine, 60 servings",
    description: "Supports muscle building, strength, and performance. 100% pure micronized creatine monohydrate.",
    price: 19.99,
    compare_at_price: 27.99,
    average_rating: 4.9,
    review_count: 3156,
    flavor: "Unflavored",
    is_featured: true,
    category: { id: "3", slug: "creatine", name: "Creatine", description: null, image_url: null, parent_id: null, position: 3, is_active: true },
    brand: { id: "1", slug: "optimum-nutrition", name: "Optimum Nutrition", description: null, logo_url: null, website_url: null, is_active: true },
    ingredients: "Creatine Monohydrate",
    servings: 60,
    serving_size: "1 Teaspoon (5g)",
  },
  {
    id: "4",
    slug: "essential-amino-energy",
    name: "Essential Amino Energy",
    short_description: "5g amino acids, natural caffeine",
    description: "Use any time to support essential amino acid delivery, muscle recovery, energy and focus.",
    price: 24.99,
    compare_at_price: 29.99,
    average_rating: 4.7,
    review_count: 1456,
    flavor: "Concord Grape",
    is_featured: true,
    category: { id: "5", slug: "amino-acids", name: "Amino Acids", description: null, image_url: null, parent_id: null, position: 5, is_active: true },
    brand: { id: "1", slug: "optimum-nutrition", name: "Optimum Nutrition", description: null, logo_url: null, website_url: null, is_active: true },
    ingredients: "Amino Blend, Energy Blend, Citric Acid, Natural and Artificial Flavor.",
    servings: 30,
    serving_size: "2 Scoops (9g)",
  },
  {
    id: "5",
    slug: "ghost-legend-pre-workout",
    name: "GHOST Legend Pre-Workout",
    short_description: "250mg caffeine, epic pumps",
    description: "GHOST LEGEND pre-workout combines a stand-out energy and focus formula with premium pump ingredients.",
    price: 44.99,
    compare_at_price: 49.99,
    average_rating: 4.8,
    review_count: 854,
    flavor: "Sonic Cherry Limeade",
    is_featured: false,
    category: { id: "2", slug: "pre-workout", name: "Pre-Workout", description: null, image_url: null, parent_id: null, position: 2, is_active: true },
    brand: { id: "4", slug: "ghost", name: "GHOST", description: null, logo_url: null, website_url: null, is_active: true },
    ingredients: "L-Citrulline, Beta-Alanine, Nitrosigine, Senactiv, Natural Caffeine.",
    servings: 25,
    serving_size: "1 Scoop (14.5g)",
  },
  {
    id: "6",
    slug: "iso100-hydrolyzed-protein",
    name: "ISO100 Hydrolyzed Protein",
    short_description: "25g protein, fast absorbing",
    description: "Super fast-digesting and absorbing hydrolyzed whey protein isolate.",
    price: 49.99,
    compare_at_price: null,
    average_rating: 4.9,
    review_count: 4120,
    flavor: "Fruity Pebbles",
    is_featured: false,
    category: { id: "1", slug: "protein", name: "Protein", description: null, image_url: null, parent_id: null, position: 1, is_active: true },
    brand: { id: "5", slug: "dymatize", name: "Dymatize", description: null, logo_url: null, website_url: null, is_active: true },
    ingredients: "Hydrolyzed Whey Protein Isolate, Whey Protein Isolate, Natural and Artificial Flavor.",
    servings: 23,
    serving_size: "1 Scoop (30g)",
  }
];
